### ISSUE TITLE
Wrong converting of uint64_t numbers 

### ISSUE THREAD

**Issue by danoldmac** [khaeransori/vscode-json2csv#18]
The main reason of issue: Wrong handling for 64 bit numbers.

Values for fields ItemsPersistentIdentifiers and system_time are shown incorrectly after converting to csv format. 
For example, I have following part of JSON file:  
      "system_time" : 1692197812390106667,
      "system_time_formatted" : "17:56:52.390",
      "timestamp" : 110867725867,
      "timestamp_formatted" : "1:50.867",
      "title" : "PlayMediaLibraryItems",
      "transport" : "usb"
    },
    "Parameters" : {
      "ItemsPersistentIdentifiers" : [
        3183234085794734210
      ],
      "ItemsStartingIndex" : 0,
      "MediaLibraryUniqueIdentifier" : "48511AF4-1979-4EAD-80CE-5FCCBF55DFBE-MPB-16.6"
    },

**Comment by khaeransori** [comment]
Hi @danoldmac ,

Thank you for bringing this issue to our attention.

The problem you mentioned regarding wrong handling for 64-bit numbers has been addressed in version 1.0.0. In this version, we've introduced lossless conversion for big integers, which ensures that 64-bit (and larger) numbers are correctly handled and quoted to preserve precision during format conversion.

Now, large integers are preserved accurately when converting between JSON and CSV, eliminating the previous issues related to number precision.

Please update to the latest version (1.0.0) and let us know if everything works as expected. If you encounter any further issues, feel free to reach out.

Thanks again for your patience and for reporting this!
