### ISSUE TITLE
Feature request: nulls

### ISSUE THREAD

**Issue by beck** [khaeransori/vscode-json2csv#3]
As is:

CSV `NULL` is converted to json str `"NULL"`

Request:

converted to json value `null`

**Comment by khaeransori** [comment]
Hi @beck 

I can repro the issue when the CSV is not using lowercased `null` (e.g `NuLl`, `nulL`).
Let see what I can do to help.

**Comment by khaeransori** [comment]
Hi @beck 

This kind of issue is already fixed in the 1.0.0, please adjust the `json2csv.toJSON.parseStringLiteralNull` configuration to `true`. Thanks for your report
