### ISSUE TITLE
Default saving as JSON

### ISSUE THREAD

**Issue by MiguelAtTweddle** [khaeransori/vscode-json2csv#8]
How can the generated JSON be saved as a file with a JSON extension instead of overwriting the original CSV file?

**Comment by mikepianka** [comment]
Just do a Save As with .json extension.

**Comment by khaeransori** [comment]
Hi @MiguelAtTweddle 
in 1.0.0 I've open new document instead of overwriting the original CSV, thanks for your suggestions
